package com.intouch.hibernate;
// Generated 24.03.2016 21:30:48 by Hibernate Tools 4.3.1



/**
 * UserEventId generated by hbm2java
 */
public class UserEventId  implements java.io.Serializable {


     private long userId;
     private long eventId;

    public UserEventId() {
    }

    public UserEventId(long userId, long eventId) {
       this.userId = userId;
       this.eventId = eventId;
    }
   
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public long getEventId() {
        return this.eventId;
    }
    
    public void setEventId(long eventId) {
        this.eventId = eventId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserEventId) ) return false;
		 UserEventId castOther = ( UserEventId ) other; 
         
		 return (this.getUserId()==castOther.getUserId())
 && (this.getEventId()==castOther.getEventId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getUserId();
         result = 37 * result + (int) this.getEventId();
         return result;
   }   


}


