package com.intouch.hibernate;
// Generated 19.04.2016 15:45:16 by Hibernate Tools 4.3.1



/**
 * Comments generated by hbm2java
 */
public class Comments  implements java.io.Serializable {


     private Long id;
     private long userId;
     private long eventId;

    public Comments() {
    }

    public Comments(long userId, long eventId) {
       this.userId = userId;
       this.eventId = eventId;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public long getEventId() {
        return this.eventId;
    }
    
    public void setEventId(long eventId) {
        this.eventId = eventId;
    }




}


