package com.intouch.hibernate;
// Generated 14.05.2016 17:07:34 by Hibernate Tools 4.3.1



/**
 * Comments generated by hbm2java
 */
public class Comments  implements java.io.Serializable {


     private Long id;
     private long userId;
     private long eventId;
     private String comment;

    public Comments() {
    }

    public Comments(long userId, long eventId, String comment) {
       this.userId = userId;
       this.eventId = eventId;
       this.comment = comment;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public long getEventId() {
        return this.eventId;
    }
    
    public void setEventId(long eventId) {
        this.eventId = eventId;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


