package com.intouch.hibernate;
// Generated 01.05.2016 17:29:52 by Hibernate Tools 4.3.1



/**
 * EventMarks generated by hbm2java
 */
public class EventMarks  implements java.io.Serializable {


     private Long id;
     private long userId;
     private long eventId;
     private int mark;

    public EventMarks() {
    }

    public EventMarks(long userId, long eventId, int mark) {
       this.userId = userId;
       this.eventId = eventId;
       this.mark = mark;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public long getEventId() {
        return this.eventId;
    }
    
    public void setEventId(long eventId) {
        this.eventId = eventId;
    }
    public int getMark() {
        return this.mark;
    }
    
    public void setMark(int mark) {
        this.mark = mark;
    }




}


