package com.intouch.hibernate;
// Generated 19.04.2016 15:45:16 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Event generated by hbm2java
 */
public class Event  implements java.io.Serializable {


     private Long id;
     private String name;
     private String description;
     private String gps;
     private long creatorId;
     private Date dateTime;
     private String address;
     private Date createDate;
     private Integer typeId;
     private String city;

    public Event() {
    }

	
    public Event(String name, String gps, long creatorId, Date dateTime, String address, Date createDate, String city) {
        this.name = name;
        this.gps = gps;
        this.creatorId = creatorId;
        this.dateTime = dateTime;
        this.address = address;
        this.createDate = createDate;
        this.city = city;
    }
    public Event(String name, String description, String gps, long creatorId, Date dateTime, String address, Date createDate, Integer typeId, String city) {
       this.name = name;
       this.description = description;
       this.gps = gps;
       this.creatorId = creatorId;
       this.dateTime = dateTime;
       this.address = address;
       this.createDate = createDate;
       this.typeId = typeId;
       this.city = city;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getGps() {
        return this.gps;
    }
    
    public void setGps(String gps) {
        this.gps = gps;
    }
    public long getCreatorId() {
        return this.creatorId;
    }
    
    public void setCreatorId(long creatorId) {
        this.creatorId = creatorId;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Integer getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }




}


