package com.intouch.hibernate;
// Generated 14.04.2016 20:20:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EventType generated by hbm2java
 */
public class EventType  implements java.io.Serializable {


     private int id;
     private String typeName;
     private Set events = new HashSet(0);

    public EventType() {
    }

	
    public EventType(int id, String typeName) {
        this.id = id;
        this.typeName = typeName;
    }
    public EventType(int id, String typeName, Set events) {
       this.id = id;
       this.typeName = typeName;
       this.events = events;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
    public Set getEvents() {
        return this.events;
    }
    
    public void setEvents(Set events) {
        this.events = events;
    }




}


