package com.intouch.hibernate;
// Generated 14.04.2016 20:20:47 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Event generated by hbm2java
 */
public class Event  implements java.io.Serializable {


     private Long id;
     private EventType eventType;
     private User user;
     private String name;
     private String description;
     private String gps;
     private Date dateTime;
     private String address;
     private Date createDate;
     private String city;
     private Set userEvents = new HashSet(0);

    public Event() {
    }

	
    public Event(User user, String name, String gps, Date dateTime, String address, Date createDate, String city) {
        this.user = user;
        this.name = name;
        this.gps = gps;
        this.dateTime = dateTime;
        this.address = address;
        this.createDate = createDate;
        this.city = city;
    }
    public Event(EventType eventType, User user, String name, String description, String gps, Date dateTime, String address, Date createDate, String city, Set userEvents) {
       this.eventType = eventType;
       this.user = user;
       this.name = name;
       this.description = description;
       this.gps = gps;
       this.dateTime = dateTime;
       this.address = address;
       this.createDate = createDate;
       this.city = city;
       this.userEvents = userEvents;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public EventType getEventType() {
        return this.eventType;
    }
    
    public void setEventType(EventType eventType) {
        this.eventType = eventType;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getGps() {
        return this.gps;
    }
    
    public void setGps(String gps) {
        this.gps = gps;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public Set getUserEvents() {
        return this.userEvents;
    }
    
    public void setUserEvents(Set userEvents) {
        this.userEvents = userEvents;
    }




}


