package com.intouch.hibernate;
// Generated 07.04.2016 17:08:53 by Hibernate Tools 4.3.1



/**
 * UserSubs generated by hbm2java
 */
public class UserSubs  implements java.io.Serializable {


     private Integer id;
     private User userByUser;
     private User userBySubscriber;

    public UserSubs() {
    }

    public UserSubs(User userByUser, User userBySubscriber) {
       this.userByUser = userByUser;
       this.userBySubscriber = userBySubscriber;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUserByUser() {
        return this.userByUser;
    }
    
    public void setUserByUser(User userByUser) {
        this.userByUser = userByUser;
    }
    public User getUserBySubscriber() {
        return this.userBySubscriber;
    }
    
    public void setUserBySubscriber(User userBySubscriber) {
        this.userBySubscriber = userBySubscriber;
    }




}


