package com.intouch.hibernate;
// Generated 07.04.2016 17:08:53 by Hibernate Tools 4.3.1



/**
 * UserEvent generated by hbm2java
 */
public class UserEvent  implements java.io.Serializable {


     private Long id;
     private Event event;
     private User user;

    public UserEvent() {
    }

    public UserEvent(Event event, User user) {
       this.event = event;
       this.user = user;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


