package com.intouch.hibernate;
// Generated 23.02.2016 1:48:34 by Hibernate Tools 4.3.1



/**
 * UserEvent generated by hbm2java
 */
public class UserEvent  implements java.io.Serializable {


     private Long id;
     private long userId;
     private long eventId;

    public UserEvent() {
    }

    public UserEvent(long userId, long eventId) {
       this.userId = userId;
       this.eventId = eventId;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public long getEventId() {
        return this.eventId;
    }
    
    public void setEventId(long eventId) {
        this.eventId = eventId;
    }




}


