package com.intouch.hibernate;
// Generated 23.02.2016 1:48:34 by Hibernate Tools 4.3.1



/**
 * UserSuscriber generated by hbm2java
 */
public class UserSuscriber  implements java.io.Serializable {


     private Long id;
     private long userId;
     private long subscriberId;

    public UserSuscriber() {
    }

    public UserSuscriber(long userId, long subscriberId) {
       this.userId = userId;
       this.subscriberId = subscriberId;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public long getSubscriberId() {
        return this.subscriberId;
    }
    
    public void setSubscriberId(long subscriberId) {
        this.subscriberId = subscriberId;
    }




}


