package com.intouch.hibernate;
// Generated 14.05.2016 17:07:34 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Long id;
     private String firstName;
     private String lastName;
     private String userImage;
     private String login;
     private String password;
     private Date registrationDate;
     private Date lastVisit;
     private String token;
     private String deviceId;
     private String applicationId;
     private String email;
     private String skype;
     private String phone;

    public User() {
    }

	
    public User(String firstName, String lastName, String login, String password, Date registrationDate, Date lastVisit, String token, String deviceId) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.login = login;
        this.password = password;
        this.registrationDate = registrationDate;
        this.lastVisit = lastVisit;
        this.token = token;
        this.deviceId = deviceId;
    }
    public User(String firstName, String lastName, String userImage, String login, String password, Date registrationDate, Date lastVisit, String token, String deviceId, String applicationId, String email, String skype, String phone) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.userImage = userImage;
       this.login = login;
       this.password = password;
       this.registrationDate = registrationDate;
       this.lastVisit = lastVisit;
       this.token = token;
       this.deviceId = deviceId;
       this.applicationId = applicationId;
       this.email = email;
       this.skype = skype;
       this.phone = phone;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getUserImage() {
        return this.userImage;
    }
    
    public void setUserImage(String userImage) {
        this.userImage = userImage;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getRegistrationDate() {
        return this.registrationDate;
    }
    
    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }
    public Date getLastVisit() {
        return this.lastVisit;
    }
    
    public void setLastVisit(Date lastVisit) {
        this.lastVisit = lastVisit;
    }
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    public String getDeviceId() {
        return this.deviceId;
    }
    
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }
    public String getApplicationId() {
        return this.applicationId;
    }
    
    public void setApplicationId(String applicationId) {
        this.applicationId = applicationId;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSkype() {
        return this.skype;
    }
    
    public void setSkype(String skype) {
        this.skype = skype;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }




}


